# -*- coding: utf-8 -*-

EVENTS = [
    {
        "slug": "fed-decision-in-march-885",
        "title": "Fed decision in March?",
        "labels": {
            "Will the Fed decrease interest rates by 50+ bps after the March 2026 meeting": "50+ bps decrease",
            "Will the Fed decrease interest rates by 25 bps after the March 2026 meeting": "25 bps decrease",
            "Will there be no change in Fed interest rates after the March 2026 meeting": "No change",
            "Will the Fed increase interest rates by 25+ bps after the March 2026 meeting": "25+ bps increase",
        },
    },
    {
        "slug": "will-the-iranian-regime-fall-by-june-30",
        "title": "Will the Iranian regime fall by June 30?",
        "labels": {"Yes": "Yes"},
    },
    {
        "slug": "will-iran-close-the-strait-of-hormuz-by-2027",
        "title": "Will Iran close the Strait of Hormuz by...?",
        "labels": {
            "Will Iran close the Strait of Hormuz before 2027": "December 31",
            "Will Iran close the Strait of Hormuz by March 31": "March 31",
            "Will Iran close the Strait of Hormuz by June 30": "June 30",
        },
    },
    {
        "slug": "us-x-iran-ceasefire-by",
        "title": "US x Iran ceasefire by...?",
        "labels": {
            "US x Iran ceasefire by March 2": "March 2",
            "US x Iran ceasefire by March 6": "March 6",
            "US x Iran ceasefire by March 15": "March 15",
            "US x Iran ceasefire by March 31": "March 31",
            "US x Iran ceasefire by April 30": "April 30",
            "US x Iran ceasefire by May 31": "May 31",
            "US x Iran ceasefire by June 30": "June 30",
        },
    },
    {
        "slug": "us-iran-nuclear-deal-before-2027",
        "title": "US-Iran nuclear deal before 2027?",
        "labels": {"Yes": "Yes"},
    },
    {
        "slug": "who-will-be-next-supreme-leader-of-iran-515",
        "title": "Who will be next Supreme Leader of Iran?",
        "labels": {
            "Will there be no new Supreme Leader of Iran by June 30": "No new (Jun 30)",
            "Will Muhammad Mirbaqiri be the next Supreme Leader of Iran": "Mirbaqiri",
            "Will Mojtaba Khamenei be the next Supreme Leader of Iran": "Mojtaba Khamenei",
            "Will Reza Pahlavi be the next Supreme Leader of Iran": "Pahlavi",
            "Will Maryam Rajavi be the next Supreme Leader of Iran": "Maryam Rajavi",
            "Will Seyed Hossein Mousavian be the next Supreme Leader of Iran": "Mousavian",
            "Will Navid Shomali be the next Supreme Leader of Iran": "Shomali",
            "Will Ali Motahari be the next Supreme Leader of Iran": "Motahari",
            "Will Mostafa Pourmohammadi be the next Supreme Leader of Iran": "Pourmohammadi",
            "Will Masoud Pezeshkian be the next Supreme Leader of Iran": "Pezeshkian",
            "Will Hassan Rouhani be the next Supreme Leader of Iran": "Rouhani",
            "Will Mohammad Khatami be the next Supreme Leader of Iran": "M. Khatami",
            "Will Ali Larijani be the next Supreme Leader of Iran": "Ali Larijani",
            "Will Alireza Arafi be the next Supreme Leader of Iran": "Arafi",
            "Will Mohammad-Reza Modarresi Yazdi be the next Supreme Leader of Iran": "Modarresi Yazdi",
            "Will Mohsen Araki be the next Supreme Leader of Iran": "Araki",
            "Will Ali Asghar Hejazi be the next Supreme Leader of Iran": "Hejazi",
            "Will Mohammad Hadi Ghazanfari Khansari be the next Supreme Leader of Iran": "Ghazanfari",
            "Will Ahmad Khatami be the next Supreme Leader of Iran": "A. Khatami",
            "Will Nasir Hosseini be the next Supreme Leader of Iran": "Nasir Hosseini",
            "Will Abbas Araghchi be the next Supreme Leader of Iran": "Araghchi",
            "Will the position of Supreme Leader of Iran be abolished": "Position abolished",
            "Will Sadegh Larijani be the next Supreme Leader of Iran": "Sadegh Larijani",
            "Will Hassan Khomeini be the next Supreme Leader of Iran": "Hassan Khomeini",
            "Will Hassan Shariatmadari be the next Supreme Leader of Iran": "Shariatmadari",
            "Will Massoud Rajavi be the next Supreme Leader of Iran": "Massoud Rajavi",
            "Will Reza Pirzadeh be the next Supreme Leader of Iran": "Pirzadeh",
            "Will Mustafa Hijri be the next Supreme Leader of Iran": "Hijri",
            "Will Gholam-Ali Haddad-Adel be the next Supreme Leader of Iran": "Haddad-Adel",
            "Will Sadegh Mahsouli be the next Supreme Leader of Iran": "Mahsouli",
            "Will Saeed Jalili be the next Supreme Leader of Iran": "Jalili",
            "Will Mahmoud Ahmadinejad be the next Supreme Leader of Iran": "Ahmadinejad",
            "Will Mohammad-Bagher Ghalibaf be the next Supreme Leader of Iran": "Ghalibaf",
            "Will Hashem Hosseini Bushehri be the next Supreme Leader of Iran": "Bushehri",
            "Will Gholam-Hossein Mohseni-Eje'i be the next Supreme Leader of Iran": "Mohseni-Eje'i",
            "Will Mohsen Qomi be the next Supreme Leader of Iran": "Mohsen Qomi",
            "Will Mohammad Yasrebi be the next Supreme Leader of Iran": "Yasrebi",
            "Will Khalil Mobasher Kashani be the next Supreme Leader of Iran": "Mobasher Kashani",
            "Will Ahmad Hosseini Khorasani be the next Supreme Leader of Iran": "Hosseini Khorasani",
            "Will Ahmad Vahidi be the next Supreme Leader of Iran": "Vahidi",
        },
    },
    {
        "slug": "what-will-the-usisrael-target-in-iran-by-march-31",
        "title": "What will the US/Israel target in Iran by March 31?",
        "labels": {
            "Will Israel or the US target an Iranian nuclear facility": "Nuclear facility",
            "Will Israel or the US target an Iranian oil or gas facility": "Oil / gas facility",
            "Will Israel or the US target Fordow nuclear facility": "Fordow",
            "Will Israel or the US target Isfahan Nuclear Technology Center nuclear facility": "Isfahan NTC",
            "Will Israel or the US target Natanz Uranium Enrichment Facility": "Natanz",
        },
    },
    {
        "slug": "usisrael-strikes-iran-on",
        "title": "US/Israel strikes Iran on...?",
        "labels": {
            "Will US or Israel strike Iran on March 3, 2026": "March 3",
            "Will US or Israel strike Iran on March 4, 2026": "March 4",
            "Will US or Israel strike Iran on March 5, 2026": "March 5",
            "Will US or Israel strike Iran on March 6, 2026": "March 6",
            "Will US or Israel strike Iran on March 7, 2026": "March 7",
            "Will US or Israel strike Iran on March 8, 2026": "March 8",
            "Will US or Israel strike Iran on March 9, 2026": "March 9",
            "Will US or Israel strike Iran on March 10, 2026": "March 10",
        },
    },
    {
        "slug": "will-crude-oil-cl-hit-by-end-of-march",
        "title": "Will Crude Oil (CL) hit __ by end of March?",
        "labels": {
            "Will Crude Oil (CL) hit (HIGH) $150 by end of March": "↑ $150",
            "Will Crude Oil (CL) hit (HIGH) $120 by end of March": "↑ $120",
            "Will Crude Oil (CL) hit (HIGH) $110 by end of March": "↑ $110",
            "Will Crude Oil (CL) hit (HIGH) $100 by end of March": "↑ $100",
            "Will Crude Oil (CL) hit (HIGH) $90 by end of March": "↑ $90",
            "Will Crude Oil (CL) hit (HIGH) $80 by end of March": "↑ $80",
            "Will Crude Oil (CL) hit (HIGH) $75 by end of March": "↑ $75",
            "Will Crude Oil (CL) hit (HIGH) $70 by end of March": "↑ $70",
            "Will Crude Oil (CL) hit (LOW) $65 by end of March": "↓ $65",
            "Will Crude Oil (CL) hit (LOW) $60 by end of March": "↓ $60",
            "Will Crude Oil (CL) hit (LOW) $55 by end of March": "↓ $55",
            "Will Crude Oil (CL) hit (LOW) $50 by end of March": "↓ $50",
            "Will Crude Oil (CL) hit (LOW) $45 by end of March": "↓ $45",
            "Will Crude Oil (CL) hit (LOW) $40 by end of March": "↓ $40",
        },
    },
    {
        "slug": "us-seizes-an-iran-linked-oil-tanker-by-march-7",
        "title": "US seizes an Iran-linked oil tanker by March 7?",
        "labels": {"Yes": "Yes"},
    },
    {
        "slug": "march-inflation-us-annual",
        "title": "March Inflation US - Annual",
        "labels": {
            "Will annual inflation increase by ≤2.0% in March": "≤2.0%",
            "Will annual inflation increase by 2.1% in March": "2.1%",
            "Will annual inflation increase by 2.2% in March": "2.2%",
            "Will annual inflation increase by 2.3% in March": "2.3%",
            "Will annual inflation increase by 2.4% in March": "2.4%",
            "Will annual inflation increase by 2.5% in March": "2.5%",
            "Will annual inflation increase by 2.6% in March": "2.6%",
            "Will annual inflation increase by 2.7% in March": "2.7%",
            "Will annual inflation increase by ≥2.8% in March": "≥2.8%",
        },
    },
]
